# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mBitController.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.statusTab = QtWidgets.QWidget()
        self.statusTab.setObjectName("statusTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.statusTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stateBox = QtWidgets.QGridLayout()
        self.stateBox.setObjectName("stateBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.statusTab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_connectionState = QtWidgets.QLabel(self.statusTab)
        self.label_connectionState.setMinimumSize(QtCore.QSize(290, 0))
        self.label_connectionState.setObjectName("label_connectionState")
        self.horizontalLayout_2.addWidget(self.label_connectionState)
        self.stateBox.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.stateBox)
        self.hostBLEconfig = QtWidgets.QHBoxLayout()
        self.hostBLEconfig.setObjectName("hostBLEconfig")
        self.label = QtWidgets.QLabel(self.statusTab)
        self.label.setObjectName("label")
        self.hostBLEconfig.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hostBLEconfig.addItem(spacerItem1)
        self.hostMAC_txtBox = QtWidgets.QLineEdit(self.statusTab)
        self.hostMAC_txtBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostMAC_txtBox.sizePolicy().hasHeightForWidth())
        self.hostMAC_txtBox.setSizePolicy(sizePolicy)
        self.hostMAC_txtBox.setMinimumSize(QtCore.QSize(290, 31))
        self.hostMAC_txtBox.setMaxLength(17)
        self.hostMAC_txtBox.setObjectName("hostMAC_txtBox")
        self.hostBLEconfig.addWidget(self.hostMAC_txtBox)
        self.verticalLayout_3.addLayout(self.hostBLEconfig)
        self.remoteBLEConfig = QtWidgets.QHBoxLayout()
        self.remoteBLEConfig.setObjectName("remoteBLEConfig")
        self.label_3 = QtWidgets.QLabel(self.statusTab)
        self.label_3.setObjectName("label_3")
        self.remoteBLEConfig.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.remoteBLEConfig.addItem(spacerItem2)
        self.mBitMac_TxtBox = QtWidgets.QLineEdit(self.statusTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mBitMac_TxtBox.sizePolicy().hasHeightForWidth())
        self.mBitMac_TxtBox.setSizePolicy(sizePolicy)
        self.mBitMac_TxtBox.setMinimumSize(QtCore.QSize(290, 31))
        self.mBitMac_TxtBox.setMaxLength(17)
        self.mBitMac_TxtBox.setObjectName("mBitMac_TxtBox")
        self.remoteBLEConfig.addWidget(self.mBitMac_TxtBox)
        self.verticalLayout_3.addLayout(self.remoteBLEConfig)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.connectButton = QtWidgets.QPushButton(self.statusTab)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout_3.addWidget(self.connectButton)
        self.tabWidget.addTab(self.statusTab, "")
        self.matrixTab = QtWidgets.QWidget()
        self.matrixTab.setEnabled(True)
        self.matrixTab.setObjectName("matrixTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.matrixTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_MatrixState = QtWidgets.QGroupBox(self.matrixTab)
        self.groupBox_MatrixState.setObjectName("groupBox_MatrixState")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_MatrixState)
        self.verticalLayout.setObjectName("verticalLayout")
        self.matrix0 = QtWidgets.QWidget(self.groupBox_MatrixState)
        self.matrix0.setObjectName("matrix0")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.matrix0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.row0 = QtWidgets.QCheckBox(self.matrix0)
        self.row0.setText("")
        self.row0.setObjectName("row0")
        self.horizontalLayout_6.addWidget(self.row0)
        self.row0_2 = QtWidgets.QCheckBox(self.matrix0)
        self.row0_2.setText("")
        self.row0_2.setObjectName("row0_2")
        self.horizontalLayout_6.addWidget(self.row0_2)
        self.row0_3 = QtWidgets.QCheckBox(self.matrix0)
        self.row0_3.setText("")
        self.row0_3.setObjectName("row0_3")
        self.horizontalLayout_6.addWidget(self.row0_3)
        self.row0_4 = QtWidgets.QCheckBox(self.matrix0)
        self.row0_4.setText("")
        self.row0_4.setObjectName("row0_4")
        self.horizontalLayout_6.addWidget(self.row0_4)
        self.row0_5 = QtWidgets.QCheckBox(self.matrix0)
        self.row0_5.setText("")
        self.row0_5.setObjectName("row0_5")
        self.horizontalLayout_6.addWidget(self.row0_5)
        spacerItem5 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.matrix0)
        self.matrix1 = QtWidgets.QWidget(self.groupBox_MatrixState)
        self.matrix1.setObjectName("matrix1")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.matrix1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem6 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.row0_21 = QtWidgets.QCheckBox(self.matrix1)
        self.row0_21.setText("")
        self.row0_21.setObjectName("row0_21")
        self.horizontalLayout_11.addWidget(self.row0_21)
        self.row0_22 = QtWidgets.QCheckBox(self.matrix1)
        self.row0_22.setText("")
        self.row0_22.setObjectName("row0_22")
        self.horizontalLayout_11.addWidget(self.row0_22)
        self.row0_23 = QtWidgets.QCheckBox(self.matrix1)
        self.row0_23.setText("")
        self.row0_23.setObjectName("row0_23")
        self.horizontalLayout_11.addWidget(self.row0_23)
        self.row0_24 = QtWidgets.QCheckBox(self.matrix1)
        self.row0_24.setText("")
        self.row0_24.setObjectName("row0_24")
        self.horizontalLayout_11.addWidget(self.row0_24)
        self.row0_25 = QtWidgets.QCheckBox(self.matrix1)
        self.row0_25.setText("")
        self.row0_25.setObjectName("row0_25")
        self.horizontalLayout_11.addWidget(self.row0_25)
        spacerItem7 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout.addWidget(self.matrix1)
        self.matrix2 = QtWidgets.QWidget(self.groupBox_MatrixState)
        self.matrix2.setObjectName("matrix2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.matrix2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem8 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.row0_16 = QtWidgets.QCheckBox(self.matrix2)
        self.row0_16.setText("")
        self.row0_16.setObjectName("row0_16")
        self.horizontalLayout_10.addWidget(self.row0_16)
        self.row0_17 = QtWidgets.QCheckBox(self.matrix2)
        self.row0_17.setText("")
        self.row0_17.setObjectName("row0_17")
        self.horizontalLayout_10.addWidget(self.row0_17)
        self.row0_18 = QtWidgets.QCheckBox(self.matrix2)
        self.row0_18.setText("")
        self.row0_18.setObjectName("row0_18")
        self.horizontalLayout_10.addWidget(self.row0_18)
        self.row0_19 = QtWidgets.QCheckBox(self.matrix2)
        self.row0_19.setText("")
        self.row0_19.setObjectName("row0_19")
        self.horizontalLayout_10.addWidget(self.row0_19)
        self.row0_20 = QtWidgets.QCheckBox(self.matrix2)
        self.row0_20.setText("")
        self.row0_20.setObjectName("row0_20")
        self.horizontalLayout_10.addWidget(self.row0_20)
        spacerItem9 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout.addWidget(self.matrix2)
        self.matrix3 = QtWidgets.QWidget(self.groupBox_MatrixState)
        self.matrix3.setObjectName("matrix3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.matrix3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.row0_6 = QtWidgets.QCheckBox(self.matrix3)
        self.row0_6.setText("")
        self.row0_6.setObjectName("row0_6")
        self.horizontalLayout_7.addWidget(self.row0_6)
        self.row0_7 = QtWidgets.QCheckBox(self.matrix3)
        self.row0_7.setText("")
        self.row0_7.setObjectName("row0_7")
        self.horizontalLayout_7.addWidget(self.row0_7)
        self.row0_8 = QtWidgets.QCheckBox(self.matrix3)
        self.row0_8.setText("")
        self.row0_8.setObjectName("row0_8")
        self.horizontalLayout_7.addWidget(self.row0_8)
        self.row0_9 = QtWidgets.QCheckBox(self.matrix3)
        self.row0_9.setText("")
        self.row0_9.setObjectName("row0_9")
        self.horizontalLayout_7.addWidget(self.row0_9)
        self.row0_10 = QtWidgets.QCheckBox(self.matrix3)
        self.row0_10.setText("")
        self.row0_10.setObjectName("row0_10")
        self.horizontalLayout_7.addWidget(self.row0_10)
        spacerItem11 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout.addWidget(self.matrix3)
        self.matrix4 = QtWidgets.QWidget(self.groupBox_MatrixState)
        self.matrix4.setObjectName("matrix4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.matrix4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem12 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.row0_11 = QtWidgets.QCheckBox(self.matrix4)
        self.row0_11.setText("")
        self.row0_11.setObjectName("row0_11")
        self.horizontalLayout_9.addWidget(self.row0_11)
        self.row0_12 = QtWidgets.QCheckBox(self.matrix4)
        self.row0_12.setText("")
        self.row0_12.setObjectName("row0_12")
        self.horizontalLayout_9.addWidget(self.row0_12)
        self.row0_13 = QtWidgets.QCheckBox(self.matrix4)
        self.row0_13.setText("")
        self.row0_13.setObjectName("row0_13")
        self.horizontalLayout_9.addWidget(self.row0_13)
        self.row0_14 = QtWidgets.QCheckBox(self.matrix4)
        self.row0_14.setText("")
        self.row0_14.setObjectName("row0_14")
        self.horizontalLayout_9.addWidget(self.row0_14)
        self.row0_15 = QtWidgets.QCheckBox(self.matrix4)
        self.row0_15.setText("")
        self.row0_15.setObjectName("row0_15")
        self.horizontalLayout_9.addWidget(self.row0_15)
        spacerItem13 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.verticalLayout.addWidget(self.matrix4)
        self.matrixClear = QtWidgets.QPushButton(self.groupBox_MatrixState)
        self.matrixClear.setObjectName("matrixClear")
        self.verticalLayout.addWidget(self.matrixClear)
        self.gridLayout_2.addWidget(self.groupBox_MatrixState, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openGifButton = QtWidgets.QPushButton(self.matrixTab)
        self.openGifButton.setObjectName("openGifButton")
        self.horizontalLayout.addWidget(self.openGifButton)
        self.gifStateButton = QtWidgets.QPushButton(self.matrixTab)
        self.gifStateButton.setEnabled(False)
        self.gifStateButton.setObjectName("gifStateButton")
        self.horizontalLayout.addWidget(self.gifStateButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.groupBox_ShowText = QtWidgets.QGroupBox(self.matrixTab)
        self.groupBox_ShowText.setObjectName("groupBox_ShowText")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_ShowText)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ShowText_LineEdit = QtWidgets.QLineEdit(self.groupBox_ShowText)
        self.ShowText_LineEdit.setMinimumSize(QtCore.QSize(500, 0))
        self.ShowText_LineEdit.setObjectName("ShowText_LineEdit")
        self.horizontalLayout_4.addWidget(self.ShowText_LineEdit)
        spacerItem14 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.pushButton_showText = QtWidgets.QPushButton(self.groupBox_ShowText)
        self.pushButton_showText.setObjectName("pushButton_showText")
        self.horizontalLayout_4.addWidget(self.pushButton_showText)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_ShowText)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.scrollSpeedSlider = QtWidgets.QSlider(self.groupBox_ShowText)
        self.scrollSpeedSlider.setMinimumSize(QtCore.QSize(500, 0))
        self.scrollSpeedSlider.setMaximum(500)
        self.scrollSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scrollSpeedSlider.setObjectName("scrollSpeedSlider")
        self.horizontalLayout_5.addWidget(self.scrollSpeedSlider)
        spacerItem15 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.scrollSpeedLabel = QtWidgets.QLabel(self.groupBox_ShowText)
        self.scrollSpeedLabel.setObjectName("scrollSpeedLabel")
        self.horizontalLayout_5.addWidget(self.scrollSpeedLabel)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_ShowText, 2, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 1, 0, 1, 1)
        self.tabWidget.addTab(self.matrixTab, "")
        self.miscStateTab = QtWidgets.QWidget()
        self.miscStateTab.setObjectName("miscStateTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.miscStateTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.miscStateTab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lcdNumber_temp = QtWidgets.QLCDNumber(self.miscStateTab)
        self.lcdNumber_temp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_temp.setObjectName("lcdNumber_temp")
        self.horizontalLayout_8.addWidget(self.lcdNumber_temp)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem17)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem18, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.miscStateTab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem19)
        self.pushButton_mBitA = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_mBitA.setCheckable(True)
        self.pushButton_mBitA.setChecked(False)
        self.pushButton_mBitA.setObjectName("pushButton_mBitA")
        self.horizontalLayout_3.addWidget(self.pushButton_mBitA)
        self.pushButton_mBitB = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_mBitB.setCheckable(True)
        self.pushButton_mBitB.setObjectName("pushButton_mBitB")
        self.horizontalLayout_3.addWidget(self.pushButton_mBitB)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem20)
        self.gridLayout_4.addWidget(self.groupBox, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.miscStateTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        self.lcdNumber_X = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_X.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_X.setObjectName("lcdNumber_X")
        self.horizontalLayout_15.addWidget(self.lcdNumber_X)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem21)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_16.addWidget(self.label_10)
        self.lcdNumber_Y = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_Y.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Y.setObjectName("lcdNumber_Y")
        self.horizontalLayout_16.addWidget(self.lcdNumber_Y)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem22)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11)
        self.lcdNumber_Z = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_Z.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Z.setObjectName("lcdNumber_Z")
        self.horizontalLayout_17.addWidget(self.lcdNumber_Z)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem23)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.miscStateTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "mBit Controller"))
        self.label_2.setText(_translate("MainWindow", "Connection State:"))
        self.label_connectionState.setText(_translate("MainWindow", "Disconnected"))
        self.label.setText(_translate("MainWindow", "Host bluetooth MAC address:"))
        self.label_3.setText(_translate("MainWindow", "Remote Micro Bit Address:"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statusTab), _translate("MainWindow", "Device Status"))
        self.groupBox_MatrixState.setTitle(_translate("MainWindow", "Pixel Matrix State"))
        self.matrixClear.setText(_translate("MainWindow", "Clear"))
        self.openGifButton.setText(_translate("MainWindow", "Load Gif"))
        self.gifStateButton.setText(_translate("MainWindow", "Play"))
        self.groupBox_ShowText.setTitle(_translate("MainWindow", "Show Text"))
        self.pushButton_showText.setText(_translate("MainWindow", "Show"))
        self.label_4.setText(_translate("MainWindow", "Speed:"))
        self.scrollSpeedLabel.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.matrixTab), _translate("MainWindow", "LED Matrix"))
        self.label_6.setText(_translate("MainWindow", "Temperature:"))
        self.groupBox.setTitle(_translate("MainWindow", "Buttons"))
        self.pushButton_mBitA.setText(_translate("MainWindow", "A"))
        self.pushButton_mBitB.setText(_translate("MainWindow", "B"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Accelerometer"))
        self.label_9.setText(_translate("MainWindow", "X:"))
        self.label_10.setText(_translate("MainWindow", "Y:"))
        self.label_11.setText(_translate("MainWindow", "Z:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.miscStateTab), _translate("MainWindow", "MicroBit State"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

